### ISSUE TITLE
Route

### ISSUE THREAD

**Issue by bnavade** [clevertech/YiiBackbone#6]
How does yii index route request and hand it to the backbone app I mean http://yiibackbone.int.clevertech.biz/#post/list. Thanks again for the head start.

**Comment by rinatio** [comment]
Hi, @bnavade . The application is generally created using approach described there: http://backbonetutorials.com/organizing-backbone-using-modules/. But instead of index.html it uses protected/views/layouts/main.php to connect requirejs. The routes are handled by backbone.js router. Yii basically just renders init page and handles ajax requests, that's all.

**Comment by bnavade** [comment]
Thanks. That is what I needed. That was quick.
